/**
 * Nationalities for the profile's dropdown — every UN member state plus the
 * two observer states, as [country, nationality] pairs.
 *
 * The profile stores the nationality ("Pakistani"). Older records hold the
 * country instead ("Pakistan"), so `toNationality` reads either and gives
 * back the nationality, which is what the dropdown selects.
 */
export const COUNTRY_NATIONALITY: [string, string][] = [
  ['Afghanistan', 'Afghan'],
  ['Albania', 'Albanian'],
  ['Algeria', 'Algerian'],
  ['Andorra', 'Andorran'],
  ['Angola', 'Angolan'],
  ['Antigua and Barbuda', 'Antiguan and Barbudan'],
  ['Argentina', 'Argentine'],
  ['Armenia', 'Armenian'],
  ['Australia', 'Australian'],
  ['Austria', 'Austrian'],
  ['Azerbaijan', 'Azerbaijani'],
  ['Bahamas', 'Bahamian'],
  ['Bahrain', 'Bahraini'],
  ['Bangladesh', 'Bangladeshi'],
  ['Barbados', 'Barbadian'],
  ['Belarus', 'Belarusian'],
  ['Belgium', 'Belgian'],
  ['Belize', 'Belizean'],
  ['Benin', 'Beninese'],
  ['Bhutan', 'Bhutanese'],
  ['Bolivia', 'Bolivian'],
  ['Bosnia and Herzegovina', 'Bosnian and Herzegovinian'],
  ['Botswana', 'Botswanan'],
  ['Brazil', 'Brazilian'],
  ['Brunei', 'Bruneian'],
  ['Bulgaria', 'Bulgarian'],
  ['Burkina Faso', 'Burkinabé'],
  ['Burundi', 'Burundian'],
  ['Cabo Verde', 'Cabo Verdean'],
  ['Cambodia', 'Cambodian'],
  ['Cameroon', 'Cameroonian'],
  ['Canada', 'Canadian'],
  ['Central African Republic', 'Central African'],
  ['Chad', 'Chadian'],
  ['Chile', 'Chilean'],
  ['China', 'Chinese'],
  ['Colombia', 'Colombian'],
  ['Comoros', 'Comorian'],
  ['Congo', 'Congolese'],
  ['Costa Rica', 'Costa Rican'],
  ['Côte d’Ivoire', 'Ivorian'],
  ['Croatia', 'Croatian'],
  ['Cuba', 'Cuban'],
  ['Cyprus', 'Cypriot'],
  ['Czechia', 'Czech'],
  ['Democratic Republic of the Congo', 'Congolese (DRC)'],
  ['Denmark', 'Danish'],
  ['Djibouti', 'Djiboutian'],
  ['Dominica', 'Dominican (Dominica)'],
  ['Dominican Republic', 'Dominican'],
  ['Ecuador', 'Ecuadorian'],
  ['Egypt', 'Egyptian'],
  ['El Salvador', 'Salvadoran'],
  ['Equatorial Guinea', 'Equatorial Guinean'],
  ['Eritrea', 'Eritrean'],
  ['Estonia', 'Estonian'],
  ['Eswatini', 'Swazi'],
  ['Ethiopia', 'Ethiopian'],
  ['Fiji', 'Fijian'],
  ['Finland', 'Finnish'],
  ['France', 'French'],
  ['Gabon', 'Gabonese'],
  ['Gambia', 'Gambian'],
  ['Georgia', 'Georgian'],
  ['Germany', 'German'],
  ['Ghana', 'Ghanaian'],
  ['Greece', 'Greek'],
  ['Grenada', 'Grenadian'],
  ['Guatemala', 'Guatemalan'],
  ['Guinea', 'Guinean'],
  ['Guinea-Bissau', 'Bissau-Guinean'],
  ['Guyana', 'Guyanese'],
  ['Haiti', 'Haitian'],
  ['Holy See', 'Vatican'],
  ['Honduras', 'Honduran'],
  ['Hungary', 'Hungarian'],
  ['Iceland', 'Icelandic'],
  ['India', 'Indian'],
  ['Indonesia', 'Indonesian'],
  ['Iran', 'Iranian'],
  ['Iraq', 'Iraqi'],
  ['Ireland', 'Irish'],
  ['Israel', 'Israeli'],
  ['Italy', 'Italian'],
  ['Jamaica', 'Jamaican'],
  ['Japan', 'Japanese'],
  ['Jordan', 'Jordanian'],
  ['Kazakhstan', 'Kazakh'],
  ['Kenya', 'Kenyan'],
  ['Kiribati', 'I-Kiribati'],
  ['Kuwait', 'Kuwaiti'],
  ['Kyrgyzstan', 'Kyrgyz'],
  ['Laos', 'Lao'],
  ['Latvia', 'Latvian'],
  ['Lebanon', 'Lebanese'],
  ['Lesotho', 'Basotho'],
  ['Liberia', 'Liberian'],
  ['Libya', 'Libyan'],
  ['Liechtenstein', 'Liechtensteiner'],
  ['Lithuania', 'Lithuanian'],
  ['Luxembourg', 'Luxembourgish'],
  ['Madagascar', 'Malagasy'],
  ['Malawi', 'Malawian'],
  ['Malaysia', 'Malaysian'],
  ['Maldives', 'Maldivian'],
  ['Mali', 'Malian'],
  ['Malta', 'Maltese'],
  ['Marshall Islands', 'Marshallese'],
  ['Mauritania', 'Mauritanian'],
  ['Mauritius', 'Mauritian'],
  ['Mexico', 'Mexican'],
  ['Micronesia', 'Micronesian'],
  ['Moldova', 'Moldovan'],
  ['Monaco', 'Monégasque'],
  ['Mongolia', 'Mongolian'],
  ['Montenegro', 'Montenegrin'],
  ['Morocco', 'Moroccan'],
  ['Mozambique', 'Mozambican'],
  ['Myanmar', 'Burmese'],
  ['Namibia', 'Namibian'],
  ['Nauru', 'Nauruan'],
  ['Nepal', 'Nepali'],
  ['Netherlands', 'Dutch'],
  ['New Zealand', 'New Zealander'],
  ['Nicaragua', 'Nicaraguan'],
  ['Niger', 'Nigerien'],
  ['Nigeria', 'Nigerian'],
  ['North Korea', 'North Korean'],
  ['North Macedonia', 'Macedonian'],
  ['Norway', 'Norwegian'],
  ['Oman', 'Omani'],
  ['Pakistan', 'Pakistani'],
  ['Palau', 'Palauan'],
  ['Palestine', 'Palestinian'],
  ['Panama', 'Panamanian'],
  ['Papua New Guinea', 'Papua New Guinean'],
  ['Paraguay', 'Paraguayan'],
  ['Peru', 'Peruvian'],
  ['Philippines', 'Filipino'],
  ['Poland', 'Polish'],
  ['Portugal', 'Portuguese'],
  ['Qatar', 'Qatari'],
  ['Romania', 'Romanian'],
  ['Russia', 'Russian'],
  ['Rwanda', 'Rwandan'],
  ['Saint Kitts and Nevis', 'Kittitian and Nevisian'],
  ['Saint Lucia', 'Saint Lucian'],
  ['Saint Vincent and the Grenadines', 'Vincentian'],
  ['Samoa', 'Samoan'],
  ['San Marino', 'Sammarinese'],
  ['São Tomé and Príncipe', 'São Toméan'],
  ['Saudi Arabia', 'Saudi'],
  ['Senegal', 'Senegalese'],
  ['Serbia', 'Serbian'],
  ['Seychelles', 'Seychellois'],
  ['Sierra Leone', 'Sierra Leonean'],
  ['Singapore', 'Singaporean'],
  ['Slovakia', 'Slovak'],
  ['Slovenia', 'Slovenian'],
  ['Solomon Islands', 'Solomon Islander'],
  ['Somalia', 'Somali'],
  ['South Africa', 'South African'],
  ['South Korea', 'South Korean'],
  ['South Sudan', 'South Sudanese'],
  ['Spain', 'Spanish'],
  ['Sri Lanka', 'Sri Lankan'],
  ['Sudan', 'Sudanese'],
  ['Suriname', 'Surinamese'],
  ['Sweden', 'Swedish'],
  ['Switzerland', 'Swiss'],
  ['Syria', 'Syrian'],
  ['Tajikistan', 'Tajik'],
  ['Tanzania', 'Tanzanian'],
  ['Thailand', 'Thai'],
  ['Timor-Leste', 'Timorese'],
  ['Togo', 'Togolese'],
  ['Tonga', 'Tongan'],
  ['Trinidad and Tobago', 'Trinidadian and Tobagonian'],
  ['Tunisia', 'Tunisian'],
  ['Türkiye', 'Turkish'],
  ['Turkmenistan', 'Turkmen'],
  ['Tuvalu', 'Tuvaluan'],
  ['Uganda', 'Ugandan'],
  ['Ukraine', 'Ukrainian'],
  ['United Arab Emirates', 'Emirati'],
  ['United Kingdom', 'British'],
  ['United States', 'American'],
  ['Uruguay', 'Uruguayan'],
  ['Uzbekistan', 'Uzbek'],
  ['Vanuatu', 'Ni-Vanuatu'],
  ['Venezuela', 'Venezuelan'],
  ['Vietnam', 'Vietnamese'],
  ['Yemen', 'Yemeni'],
  ['Zambia', 'Zambian'],
  ['Zimbabwe', 'Zimbabwean'],
]

/** Pakistani first — nearly everyone at Convertt — then A to Z. */
export const NATIONALITIES: string[] = [
  'Pakistani',
  ...COUNTRY_NATIONALITY.map(([, n]) => n).filter((n) => n !== 'Pakistani').sort((a, b) => a.localeCompare(b)),
]

/** "Pakistan", "pakistani " and "Pakistani" all come back "Pakistani". Unknown text is returned trimmed, as it was. */
export function toNationality(raw: string | null | undefined): string | null {
  const s = raw?.trim()
  if (!s) return null
  const low = s.toLowerCase()
  const hit = COUNTRY_NATIONALITY.find(([c, n]) => c.toLowerCase() === low || n.toLowerCase() === low)
  return hit ? hit[1] : s
}
