/**
 * Employment Letter builder — pick an employee, the fields fill in, edit what
 * differs for this offer, then save a draft, preview, or print.
 *
 * The letter itself is generated by the shared document generator, so the
 * builder is just the front of it: it collects the fields and hands them to the
 * same generate route the profile button uses.
 *
 * HR only.
 */
import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'
import { verifyToken } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import { EmploymentLetterBuilder } from './builder'

export default async function EmploymentLetterPage() {
  const cookieStore = await cookies()
  const payload = await verifyToken(cookieStore.get('hr_token')?.value)
  if (!payload) redirect('/login')
  const role = cookieStore.get('hr_preview_role')?.value ?? payload.role
  if (role !== 'HR_ADMIN') {
    return (
      <div className="rounded-2xl bg-slate-50 border border-slate-100 p-6">
        <h2 className="text-lg font-semibold text-slate-900">Access denied</h2>
        <p className="text-sm text-slate-600 mt-2">The letter builder is HR-only.</p>
      </div>
    )
  }

  const staff = await prisma.employee.findMany({
    where: { deletedAt: null, status: { notIn: ['RESIGNED', 'TERMINATED', 'INACTIVE', 'LAYOFF'] } },
    select: { id: true, fullName: true, employeeCode: true, designation: true },
    orderBy: { fullName: 'asc' },
  })

  return (
    <EmploymentLetterBuilder
      staff={staff.map((s) => ({
        id: s.id, fullName: s.fullName, employeeCode: s.employeeCode,
        designation: s.designation,
      }))}
    />
  )
}
